version: 1.0
provider:
  name: openfaas
functions:
  openfaas-imageui:
    lang: golang-http
    handler: ./openfaas-imageui
    image: servernull/openfaas-imageui:0.1.0
    environment:
      read_timeout: 120
      write_timeout: 120
      exec_timeout: 120
